@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

LAYOUT_WITH_LEGEND()
LAYOUT_LEFT_RIGHT()

title C4 Context Diagram — Health (TO-BE)
Person(patient, "Пациент", "Записывается на прием")
Person(doctor, "Врач", "Упhавляет расписанием, просматривает анализы, пациентов")
Person(laborant, "Лаборант", "Просматривает результаты анализов в LIS (контроль)")

Container(apiGateway, "Внешний API Gateway")
Container(mobileApp, "Мобильное приложение", "", "Запись на приём, оплата услуг, просмотр результатов анализов")
Container(laboratory, "LIS (Лаборатория)", "", "SOAP/FTP")
Container(analysis, "Анализы", "", "")
Container(webPortal, "Веб-портал", "", "Текущий интерфейс для пациентов, врачей и администраторов")

Rel(laborant, laboratory, "Просматривает результаты анализов", "UI / API")
Rel(laboratory, apiGateway, "Передача результатов анализов", "Пакетная выгрузка")
Rel(apiGateway, analysis, "Передача результатов анализов", "Internal Call")
Rel(apiGateway, webPortal, "Передача результатов анализов", "grpc")

@enduml